spring:
  application:
    name: CATALOG-SERVICE

  config:
    import: optional:configserver:http://localhost:8888

  profiles:
    active: local

  cloud:
    config:
      fail-fast: true
      retry:
        initial-interval: 2000
        max-attempts: 10

  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    username: root
    password: Aishu@123
    url: jdbc:mysql://localhost:3306/revplay?createDatabaseIfNotExist=true
